name: hm_imoveis_pim
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  google_fonts: ^1.1.1
  font_awesome_flutter: ^8.10.0
  provider: ^4.3.2+2
  http: ^0.12.2
  shared_preferences: ^0.5.12+2
  carousel_pro: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.3.0
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
#  ios: true
  image_path: "assets_dev/icon.png"
  adaptive_icon_background: "#00509d"
  adaptive_icon_foreground: "assets_dev/icon-adaptive.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 700

