class InformationBitcoins {
  String text1 =
      'Bitcoin é uma moeda digital, descentralizada e que não necessita de terceiros para funcionar. Isso significa que você não depende de bancos, grandes corporações ou governos para movimentar o seu dinheiro. Com o Bitcoin, o dinheiro é realmente seu.\n\nO Bitcoin foi a primeira criptomoeda do mundo e há oito anos funciona sem qualquer interrupção, baseada em uma rede descentralizada extremamente segura chamada Blockchain criada por Satoshi Nakamoto.';
  String text2 =
      'O Bitcoin tem diversas propriedades e formas de uso, mas vamos abordar uma bem específica: bitcoin como moeda.\n\nMas quais as vantagens do bitcoin como moeda?\n\nSão muitas! Vamos ressaltar as principais: liberdade de pagamento, taxas menores, segurança, privacidade, controle e transparência.\n\nNenhum Bitcoin pode ser confiscado, você pode mandá-lo para quem quiser pagando taxas menores. Além disso, ele é seguro e dá mais privacidade, controle e transparência nas negociações. Contudo, o Bitcoin pode ser utilizado também como investimento para que está procurando diversificar seu patrimônio para ter melhores ganhos.\n\nO Bitcoin trouxe excelentes retornos e a tendência é que ele se torne mais popular a longo prazo.';
  String text3 =
      'Atualmente existem três maneiras de adquirir bitcoins de maneira eficiente: através da mineração, comprando em exchanges ou comprando diretamente com outras pessoas.\n\nMinerar\n\nÉ possível adquirir Bitcoins através da mineração. Você vai precisar comprar um computador específico para isso e ceder seu poder computacional para a rede, confirmando transações. Para isso, você será recompensando com bitcoins a cada bloco minerado.\n\nAtualmente não é viável minerar no Brasil, porque o custo de eletricidade é muito alto.\n\nFoxBit\n\nDá para adquirir bitcoins através de Exchanges como a Foxbit. As exchanges são sites que reúnem compradores e vendedores em um ambiente seguro, onde as trocas ocorrem de forma anônima e rápida.\n\nP2P\n\nTambém é possível comprar Bitcoins diretamente com outras pessoas, sem precisar passar por uma exchange.\n\nO problema é que você vai precisar encontrar alguém de confiança e que conheça bitcoin, porque golpes nesse tipo de transação são comuns.';
  String text4 =
      'Uma dúvida muito comum é sobre a segurança do Bitcoin. É seguro ter bitcoin?\n\nA resposta é simples e foi dada no vídeo acima por experts no assunto, o bitcoin é mais seguro do que o dinheiro que você tem hoje no seu banco. Conhecendo o bitcoin você vai saber o nível de segurança proporcionado por ele, é muito superior aos dos bancos tradicionais.\n\nNo Bitcoin não há um único ponto de falha, para algum ator malicioso conseguir atacar a rede seria necessário invadir milhões de computadores em todo mundo, tarefa impossível.\n\nEnquanto nos sistemas bancários tradicionais há apenas alguns servidores centrais e todas as transações ficam escondidas do público.';
  String text5 =
      'O melhor investimento para você é o que vai de acordo com o seu perfil de investidor. Por isso, para analisar se o bitcoin é uma boa opção para ser incluído em sua carteira de investimentos, procure analisar se você se encaixa no tipo de investidor que é arrojado.\n\nFaça uma análise da sua personalidade, juntamente com seus objetivos financeiros e decida se você gosta de aplicar em ativos que podem apresentar alta rentabilidade devido a sua volatilidade.\n\nOutra dica importante é contar com profissionais qualificados e empresas idôneas e confiáveis do mercado financeiro para orientá-lo da melhor forma possível.';
  String text6 =
      'No dia 31 de outubro de 2008, auge da crise do subprime, um programador usando o pseudônimo de Satoshi Nakamoto publicou o White Paper do Bitcoin, um documento descrevendo como o sistema iria funcionar.\n\nDesde então, o Bitcoin vem sendo adotado por milhões de pessoas no mundo.';
  String text7 =
      'A Laís acabou de enviar uma transação de bitcoin para o Japão e ela fez isso sem precisar abrir uma conta bancária e em apenas alguns minutos.\n\nCom o Bitcoin você é seu próprio banco, baixar uma carteira de bitcoin é como ter disponível uma agência bancária nas suas mãos 24 horas por dia.\n\nSem taxas, sem um gerente chato e capaz de transferir em instantes sua transação. Criar uma carteira de bitcoin é fácil e não custa nada.\n\nAssim como há diversas maneiras de interagir com seu banco, também é possível interagir de diversas formas com sua carteira de bitcoin, via app no smartphone, programa no seu desktop/notebook e até carteiras de papel.\n\nVamos lá criar seu próprio banco? Veja no próximo item as melhores carteiras para instalar em seu celular e computador.';
}
